import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  plugins: [react(), tailwindcss()],

  server: {
    port: 5173,
    proxy: {
      // API
      "/api": { target: "http://localhost:5000", changeOrigin: true },
      // SEO endpoints are generated by the API from the database, so they are
      // proxied in development too — otherwise /sitemap.xml 404s locally and
      // behaves differently from production.
      "/sitemap.xml": { target: "http://localhost:5000", changeOrigin: true },
      "/robots.txt": { target: "http://localhost:5000", changeOrigin: true },
    },
  },

  preview: {
    port: 4173,
    proxy: {
      "/api": { target: "http://localhost:5000", changeOrigin: true },
      "/sitemap.xml": { target: "http://localhost:5000", changeOrigin: true },
      "/robots.txt": { target: "http://localhost:5000", changeOrigin: true },
    },
  },

  build: {
    target: "es2020",
    cssCodeSplit: true,
    sourcemap: false,
    chunkSizeWarningLimit: 700,
    rollupOptions: {
      output: {
        /**
         * Split long-lived vendor code away from application code so a content
         * release doesn't invalidate React or the router in everyone's cache.
         * Route-level splitting is handled by React.lazy in App.jsx.
         *
         * Expressed as a function because the bundler Vite 8 ships (rolldown)
         * only accepts the functional form of `manualChunks`.
         */
        manualChunks: (id) => {
          if (!id.includes("node_modules")) return undefined;
          if (
            /[\\/]node_modules[\\/](react|react-dom|react-router|react-router-dom|scheduler)[\\/]/.test(
              id,
            )
          )
            return "vendor-react";
          if (
            /[\\/]node_modules[\\/](@reduxjs|react-redux|redux|redux-persist|immer|reselect)[\\/]/.test(
              id,
            )
          )
            return "vendor-state";
          if (
            /[\\/]node_modules[\\/](framer-motion|motion-dom|motion-utils)[\\/]/.test(
              id,
            )
          )
            return "vendor-motion";
          if (/[\\/]node_modules[\\/](react-hook-form)[\\/]/.test(id))
            return "vendor-forms";
          if (/[\\/]node_modules[\\/](axios)[\\/]/.test(id))
            return "vendor-http";
          if (/[\\/]node_modules[\\/](react-icons)[\\/]/.test(id))
            return "vendor-icons";
          return "vendor";
        },
      },
    },
  },
});
